effects:
  - type: LENGTH_BREATHING
    speed: 50
    span: 18
    pause: 50
    reverse: false
    refreshRate: 30
    minDuration: 10
    maxDuration: 2000
    colors:
      - { R: 0, G: 255, B: 0, A: 255 }
      - { R: 0, G: 0, B: 0, A: 255 }
  - type: LENGTH_BREATHING
    speed: 50
    span: 18
    pause: 50
    reverse: true
    refreshRate: 30
    minDuration: 10
    maxDuration: 2000
    colors:
      - { R: 0, G: 0, B: 255, A: 255 }
      - { R: 0, G: 0, B: 0, A: 255 }
  - type: LENGTH_BREATHING
    speed: 95
    span: 18
    pause: 50
    reverse: true
    refreshRate: 30
    minDuration: 10
    maxDuration: 2000
    colors:
      - { R: 255, G: 0, B: 0, A: 255 }
      - { R: 0, G: 0, B: 0, A: 255 }
  - type: LENGTH_BREATHING
    speed: 90
    span: 18
    pause: 50
    reverse: true
    refreshRate: 30
    minDuration: 10
    maxDuration: 2000
    colors:
      - { R: 100, G: 30, B: 200, A: 255 }
      - { R: 0, G: 0, B: 0, A: 255 }
  - type: LENGTH_BREATHING
    speed: 80
    span: 18
    pause: 50
    reverse: false
    refreshRate: 30
    minDuration: 10
    maxDuration: 2000
    colors:
      - { R: 255, G: 0, B: 0, A: 255 }
      - { R: 0, G: 0, B: 0, A: 255 }
  - type: LENGTH_BREATHING
    speed: 50
    span: 18
    pause: 50
    reverse: false
    refreshRate: 30
    minDuration: 10
    maxDuration: 2000
    colors:
      - { R: 0, G: 255, B: 0, A: 255 }
      - { R: 0, G: 0, B: 0, A: 255 }
  - type: LENGTH_BREATHING
    speed: 100
    span: 18
    pause: 50
    reverse: false
    refreshRate: 30
    minDuration: 10
    maxDuration: 2000
    colors:
      - { R: 255, G: 0, B: 255, A: 255 }
      - { R: 0, G: 0, B: 0, A: 255 }
  - type: LENGTH_BREATHING
    speed: 60
    span: 18
    pause: 50
    reverse: false
    refreshRate: 30
    minDuration: 10
    maxDuration: 2000
    colors:
      - { R: 255, G: 255, B: 0, A: 255 }
      - { R: 0, G: 0, B: 0, A: 255 }