effects:
  - type: MOVING_SEGMENTS
    speed: 100
    span: 144
    pause: 50
    reverse: false
    refreshRate: 30
    minDuration: 10
    maxDuration: 2000
    colors:
      - { R: 255, G: 0, B: 0, A: 255 }
      - { R: 0, G: 255, B: 0, A: 255 }
      - { R: 0, G: 0, B: 255, A: 255 }
